version: "3.8"
volumes:
  php-fpm-socket:
services:
  kenshu-laravel:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    container_name: kenshu-laravel
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/workspace/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=kenshu-mysql
      - DB_PORT=3306
      - DB_DATABASE=kenshudb
      - DB_USERNAME=kenshu
      - DB_PASSWORD=password

  kenshu-nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    container_name: kenshu-nginx
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/workspace/backend

  kenshu-mysql:
    build:
      context: ./infra/mysql
      dockerfile: Dockerfile
    container_name: kenshu-mysql
    ports:
      - 3306:3306
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
      - ./infra/mysql/entorypoint:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=kenshudb
      - MYSQL_USER=kenshu
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
