FROM node:14.2-alpine as node
FROM nginx:1.18-alpine

ENV TZ=Asia/Tokyo

RUN apk update && \
  apk add --update --no-cache --virtual=.build-dependencies g++

# node command
COPY --from=node /usr/local/bin /usr/local/bin
# npm command
COPY --from=node /usr/local/lib /usr/local/lib
# yarn command
COPY --from=node /opt /opt
# nginx config file
COPY ./*.conf /etc/nginx/conf.d/

WORKDIR /workspace/backend
