name: Deploy to EC2  
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: connect & deploy
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo $SECRET_KEY > secret_key