name: Deploy to EC2  
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: connect & deploy
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run:
        echo "$SECRET_KEY" > secret_key &&
        chmod 600 secret_key &&
        ssh -o StrictHostKeyChecking=no -i secret_key ${EC2_USER}@${EC2_HOST} "cd ~/kenshu-backend-laravel && git pull && sudo cp -r /home/ubuntu/kenshu-backend-laravel/backend/* /var/www/html"