name: Deploy to EC2  
on:
  push:
    branches: [ main, github-actions ]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_HOST: ${{ secrets.EC2_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Output SECRET_KEY
      run: |
        echo $SECRET_KEY > secret_key
        
    - name: Change permission
      run: |
        chmod 600 secret_key

    - name: Deploy
      run: |
        cat secret_key
        ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/kenshu-backend-laravel && git pull && sudo cp -r /home/ubuntu/kenshu-backend-laravel/backend/* /var/www/html"
