name: Deploy to EC2  
on:
  push:
    branches: [ main, github-actions ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Output SECRET_KEY
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo $SECRET_KEY > secret_key
        
    - name: Change permission
      run: |
        chmod 600 secret_key

    - name: Deploy
      run: |
        ssh ${EC2_USER}@${EC2_HOST} -i secret_key
